parameters:
  werkint_stats.statsdirector.class:
    Werkint\Bundle\StatsBundle\Service\StatsDirector
  werkint_stats.objectcachemanager.class:
    Werkint\Bundle\StatsBundle\Service\ObjectCacheManager
  werkint_stats.eventlistener.cacheproxylistener.class:
    Werkint\Bundle\StatsBundle\EventListener\CacheProxyListener
  werkint_stats.security.voter.statsvoter.class:
    Werkint\Bundle\StatsBundle\Service\Security\Voter\StatsVoter
  werkint_stats.twig.werkintstatsextension.class:
    Werkint\Bundle\StatsBundle\Service\Twig\WerkintStatsExtension

services:
  werkint_stats.statsdirector:
    class: %werkint_stats.statsdirector.class%
    arguments:
      - @security.context
      - %kernel.debug%
  werkint_stats.objectcachemanager:
    class: %werkint_stats.objectcachemanager.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @werkint_stats.statsdirector
      - @werkint_stats.normalizer
  werkint_stats.annotation_driver:
    class: Werkint\Bundle\StatsBundle\Service\Metadata\AnnotationDriver
    arguments:
      - @annotations.cached_reader
  werkint_stats.metadata_factory:
    class: Metadata\MetadataFactory
    arguments:
      - @werkint_stats.annotation_driver
  werkint_stats.eventlistener.cacheproxylistener:
    class: %werkint_stats.eventlistener.cacheproxylistener.class%
    arguments:
      - @service_container # For resolving circular reference
    tags:
      - { name: doctrine.event_subscriber }

  # Security
  werkint_stats.security.voter.statsvoter:
    class: %werkint_stats.security.voter.statsvoter.class%
    arguments:
      - @security.role_hierarchy
      - %werkint_stats.roles%
    tags:
      - { name: security.voter }

  # Twig extension
  werkint_stats.twig.werkintstatsextension:
    class: %werkint_stats.twig.werkintstatsextension.class%
    arguments:
      - @werkint_stats.statsdirector
    tags:
      - { name: twig.extension }
  werkint_stats.normalizer:
     class: Werkint\Bundle\StatsBundle\Service\Normalizer
     arguments:
        - @doctrine.orm.entity_manager