services:
    # Services
    werkint.stats:
        class: Werkint\Bundle\StatsBundle\Service\StatsDirector
        arguments:
            - @security.context
        tags:
            - { name: werkint.redis.cache, scope: root, ns: werkint.stats }
    werkint.stats.stuffprovider:
        class: Werkint\Bundle\StatsBundle\Service\StatsStuffProvider
        arguments:
            - @werkint.stats
        tags:
            - { name: werkint.stuff.provider, class: werkint.stats, tick: 10 }

    # Security
    werkint.stats.security.voter.statsvoter:
        class: Werkint\Bundle\StatsBundle\Service\Security\Voter\StatsVoter
        arguments:
            - @security.role_hierarchy
            - %werkint_stats.roles%
        tags:
            - { name: security.voter }

    # Twig extension
    werkint.stats.twig.werkintstatsextension:
        class: Werkint\Bundle\StatsBundle\Service\Twig\WerkintStatsExtension
        arguments:
            - @werkint.stats
        tags:
            - { name: twig.extension }
